# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_x_iht_mat_DynMultiNet_bin_cpp <- function(x_iht_mat, x_t_sigma_prior_inv, tau_h, y_ijt, w_ijt, s_ijt, mu_t) {
    .Call('_DynMultiNet_sample_x_iht_mat_DynMultiNet_bin_cpp', PACKAGE = 'DynMultiNet', x_iht_mat, x_t_sigma_prior_inv, tau_h, y_ijt, w_ijt, s_ijt, mu_t)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_DynMultiNet_RcppExport_registerCCallable', PACKAGE = 'DynMultiNet')
})
